apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-flask
spec:
  selector:
    matchLabels:
      run: my-flask
  replicas: 2
  template:
    metadata:
      labels:
        run: my-flask
    spec:
      containers:
      - name: my-flask
        image: aandaldi/learn-docker
        ports:
        - containerPort: 5000

