apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: flask-simple
  labels:
    run: flask-simple
    app: test-deployment
    tier: flask-simple
spec:
  replicas: 2
  template:
    metadata:
      labels:
        run: flask-simple
    spec:
      containers:
      - name: flask-simple
        image: aand/learn-flask:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
          protocol: TCP
      imagePullSecrets:
      - name: regsecret