kind: Service
apiVersion: v1
metadata:
  name: learn-docker
spec:
  selector:
    run: learn-docker
  sessionAffinity: ClientIP
  ports:
    - name: port1
      protocol: TCP
      port: 5000
      targetPort: 5000
  type: NodePort
