kind: Service
apiVersion: v1
metadata:
  name: flask-simple
  labels: 
spec:
  selector:
    run: flask-simple
  sessionAffinity: ClientIP
  ports:
    - name: port1
      protocol: TCP
      port: 5000
      #targetPort: 5000
      nodePort: 30001
  type: NodePort
