kind: PersistentVolume
apiVersion: v1
metadata:
  name: mysql-persistent-volume
  labels:
    app : test-deployment
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"