version: "2"
services:
  app:
    build: .
    depends_on: 
      - db
    ports:
      - "5000:5000"

  db:
    image: mysql:5.7
    container_name: db
    restart: always
    ports:
      - "32000:3306"
    environment: 
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_USER: root
      MYSQL_ROOT_HOST: 0.0.0.0
    volumes:
      - db_data:/var/lib/mysql
volumes: 
  db_data: