apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mysql
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: test-deployment
        tier: db
    spec:
      containers:
      - name: mysql
        image: mysql:5.6
        args:
          - "--ignore-db-dir=lost+found"
        volumeMounts:
          - name: persistent-storage-db
            mountPath: /var/lib/mysql
        env:
          - name : MYSQL_RANDOM_ROOT_PASSWORD
            value: 'yes'
          - name: MYSQL_DATABASE
            value: 'root'
          - name: MYSQL_USER
            value: 'root'
          - name: MYSQL_PASSWORD
            value: 'root'
      volumes:
        - name: persistent-storage-db
          persistentVolumeClaim:
            claimName: mysql-pv-claim



