apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: flask-app
  labels:
    # run: flask-app
    app: test-deployment
spec:
  selector:
    matchLabels:
      app: test-deployment
  replicas: 2
  template:
    metadata:
      labels:
        # run: flask-app
        app: test-deployment
    spec:
      containers:
      - name: flask-app
        image: flask-app
        imagePullPolicy: Never
        env: 
          - name : MYSQL_RANDOM_ROOT_PASSWORD
            value: 'yes'
          - name: MYSQL_USER
            value: 'root'
          - name: MYSQL_PASSWORD
            value: 'root'
        ports:
        - containerPort: 5000
          protocol: TCP
      imagePullSecrets:
      - name: regsecret