apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: flask-app
  labels:
    run: flask-app
    app: test-deployment
    tier: flask-app
spec:
  replicas: 2
  template:
    metadata:
      labels:
        run: flask-app
    spec:
      containers:
      - name: flask-app
        image: flask-app
        imagePullPolicy: Never
        env: 
          - name:  PMA_HOST
            value: mysql-service 
        ports:
        - containerPort: 5000
          protocol: TCP
      imagePullSecrets:
      - name: regsecret