apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mysql
  labels: 
    # run: flask-app
    app: test-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-deployment
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        # run: flask-app
        app: test-deployment
    spec:
      containers:
      - name: mysql
        image: mysql:5.6
        args:
          - "--ignore-db-dir=lost+found"
        volumeMounts:
          - name: persistent-storage-db
            mountPath: /var/lib/mysql
        env:
          - name : MYSQL_RANDOM_ROOT_PASSWORD
            value: 'yes'
            name: MYSQL_ROOT_PASSWORD
            value: 'root'
          - name: MYSQL_USER
            value: 'root'
          - name: MYSQL_PASSWORD
            value: 'root'
      volumes:
        - name: persistent-storage-db
          persistentVolumeClaim:
            claimName: mysql-pv-claim
        


