kind: Service
apiVersion: v1
metadata:
  name: flask-app
spec:
  selector:
    run: flask-app
  sessionAffinity: ClientIP
  ports:
    - name: port1
      protocol: TCP
      port: 5000
      targetPort: 5000
  type: NodePort
