apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  labels: 
    app: mysql
spec:
  selector:
    app: test-deployment
  ports:
  - port: 3306
    nodePort: 30036
    protocol: TCP
  type: NodePort
---

# kind: Endpoints
# apiVersion: v1
# metadata:
#   name: mysql-service
# subsets:
#   - addresses:
#       - ip: 112.6.8.4
#     ports:
#       - port: 3306