kind: Service
apiVersion: v1
metadata:
  name: flask-app
  labels: 
    app: flask-app
spec:
  selector:
    app: test-deployment
    tier: mysql
  sessionAffinity: ClientIP
  ports:
    - name: port1
      protocol: TCP
      port: 5000
      targetPort: 5000
  type: NodePort
